// RideSync Driver App — Sign Up Screen
//
// New drivers register here. On success:
//   1. Creates a Supabase Auth account (email + password)
//   2. Inserts a row into the `drivers` table (name + auth_id)
//   3. The DB auto-generates their unique short_code (e.g. DRV007)
//   4. We show them their code and save their profile locally

import React, { useState } from 'react';
import {
  View,
  Text,
  TextInput,
  TouchableOpacity,
  StyleSheet,
  ActivityIndicator,
  KeyboardAvoidingView,
  Platform,
  ScrollView,
  Alert,
} from 'react-native';
import { supabase } from '../lib/supabase';
import { saveDriverProfile } from '../lib/storage';

interface Props {
  onSignUpSuccess: (driverId: string) => void;
  onBackToLogin: () => void;
}

export default function SignUpScreen({ onSignUpSuccess, onBackToLogin }: Props) {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // After signup, we show the driver their auto-generated short code
  const [driverCode, setDriverCode] = useState<string | null>(null);
  const [driverId, setDriverId] = useState<string | null>(null);

  async function handleSignUp() {
    // Validation
    if (!name.trim()) { setError('Please enter your name.'); return; }
    if (!email.trim()) { setError('Please enter your email.'); return; }
    if (password.length < 6) { setError('Password must be at least 6 characters.'); return; }
    if (password !== confirmPassword) { setError('Passwords do not match.'); return; }

    setLoading(true);
    setError(null);

    // 1. Create Supabase Auth account
    const { data: authData, error: authErr } = await supabase.auth.signUp({
      email: email.trim(),
      password,
    });

    if (authErr || !authData.user) {
      setError(authErr?.message || 'Sign up failed. Please try again.');
      setLoading(false);
      return;
    }

    // 2. Insert driver profile (short_code is auto-generated by DB trigger)
    const { data: driverData, error: driverErr } = await supabase
      .from('drivers')
      .insert({ name: name.trim(), auth_id: authData.user.id })
      .select('id, name, short_code')
      .single();

    if (driverErr || !driverData) {
      setError('Account created but profile setup failed. Please contact support.');
      setLoading(false);
      return;
    }

    // 3. Save locally
    await saveDriverProfile({ id: driverData.id, name: driverData.name });

    setDriverCode(driverData.short_code);
    setDriverId(driverData.id);
    setLoading(false);
  }

  // ─── Success Screen ─────────────────────────────────────────────────────────
  // Show the driver their unique code before moving on

  if (driverCode && driverId) {
    return (
      <View style={styles.container}>
        <View style={styles.successCard}>
          <Text style={styles.successEmoji}>🎉</Text>
          <Text style={styles.successTitle}>You're all set!</Text>
          <Text style={styles.successSubtitle}>Your unique Driver ID is:</Text>

          <View style={styles.codeBox}>
            <Text style={styles.codeText}>{driverCode}</Text>
          </View>

          <Text style={styles.codeHint}>
            Share this code with your students so they can track your bus. You can find it again in your profile settings.
          </Text>

          <TouchableOpacity
            style={styles.continueButton}
            onPress={() => onSignUpSuccess(driverId)}
            activeOpacity={0.8}
          >
            <Text style={styles.continueButtonText}>Continue to App →</Text>
          </TouchableOpacity>
        </View>
      </View>
    );
  }

  // ─── Sign Up Form ────────────────────────────────────────────────────────────

  return (
    <KeyboardAvoidingView
      style={{ flex: 1 }}
      behavior={Platform.OS === 'ios' ? 'padding' : undefined}
    >
      <ScrollView style={styles.container} contentContainerStyle={styles.inner}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.logo}>🚌</Text>
          <Text style={styles.appName}>RideSync</Text>
          <Text style={styles.tagline}>DRIVER SIGN UP</Text>
        </View>

        {/* Form */}
        <View style={styles.form}>
          <Text style={styles.label}>Your Name</Text>
          <TextInput
            style={styles.input}
            placeholder="e.g. Ravi Kumar"
            placeholderTextColor="#475569"
            value={name}
            onChangeText={setName}
            autoCapitalize="words"
          />

          <Text style={styles.label}>Email</Text>
          <TextInput
            style={styles.input}
            placeholder="your@email.com"
            placeholderTextColor="#475569"
            value={email}
            onChangeText={setEmail}
            keyboardType="email-address"
            autoCapitalize="none"
            autoCorrect={false}
          />

          <Text style={styles.label}>Password</Text>
          <TextInput
            style={styles.input}
            placeholder="At least 6 characters"
            placeholderTextColor="#475569"
            value={password}
            onChangeText={setPassword}
            secureTextEntry
          />

          <Text style={styles.label}>Confirm Password</Text>
          <TextInput
            style={styles.input}
            placeholder="Repeat password"
            placeholderTextColor="#475569"
            value={confirmPassword}
            onChangeText={setConfirmPassword}
            secureTextEntry
          />

          {error && <Text style={styles.errorText}>{error}</Text>}

          <TouchableOpacity
            style={[styles.signUpButton, loading && { opacity: 0.6 }]}
            onPress={handleSignUp}
            disabled={loading}
            activeOpacity={0.8}
          >
            {loading ? (
              <ActivityIndicator color="#fff" />
            ) : (
              <Text style={styles.signUpButtonText}>Create Account</Text>
            )}
          </TouchableOpacity>
        </View>

        {/* Back to login */}
        <TouchableOpacity onPress={onBackToLogin} style={styles.loginLink}>
          <Text style={styles.loginLinkText}>
            Already have an account?{' '}
            <Text style={{ color: '#38BDF8' }}>Log In</Text>
          </Text>
        </TouchableOpacity>
      </ScrollView>
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0F172A',
  },
  inner: {
    paddingHorizontal: 28,
    paddingTop: 60,
    paddingBottom: 40,
  },
  header: {
    alignItems: 'center',
    marginBottom: 36,
  },
  logo: { fontSize: 48, marginBottom: 10 },
  appName: {
    fontSize: 28,
    fontWeight: '800',
    color: '#F1F5F9',
    letterSpacing: 1,
  },
  tagline: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748B',
    letterSpacing: 3,
    marginTop: 4,
  },
  form: { marginBottom: 24 },
  label: {
    fontSize: 12,
    fontWeight: '600',
    color: '#64748B',
    letterSpacing: 1,
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  input: {
    backgroundColor: '#1E293B',
    borderWidth: 1,
    borderColor: '#334155',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 15,
    color: '#E2E8F0',
    marginBottom: 16,
  },
  errorText: {
    color: '#F87171',
    fontSize: 13,
    textAlign: 'center',
    marginBottom: 12,
  },
  signUpButton: {
    backgroundColor: '#10B981',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 4,
  },
  signUpButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  loginLink: { alignItems: 'center' },
  loginLinkText: {
    fontSize: 14,
    color: '#64748B',
  },

  // ─── Success screen ────────────────────────────────────────────
  successCard: {
    flex: 1,
    backgroundColor: '#0F172A',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 32,
  },
  successEmoji: { fontSize: 56, marginBottom: 16 },
  successTitle: {
    fontSize: 28,
    fontWeight: '800',
    color: '#F1F5F9',
    marginBottom: 8,
  },
  successSubtitle: {
    fontSize: 15,
    color: '#94A3B8',
    marginBottom: 20,
  },
  codeBox: {
    backgroundColor: '#1E293B',
    borderWidth: 2,
    borderColor: '#10B981',
    borderRadius: 16,
    paddingHorizontal: 32,
    paddingVertical: 20,
    marginBottom: 16,
  },
  codeText: {
    fontSize: 36,
    fontWeight: '800',
    color: '#10B981',
    letterSpacing: 6,
  },
  codeHint: {
    fontSize: 13,
    color: '#64748B',
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: 32,
    paddingHorizontal: 8,
  },
  continueButton: {
    backgroundColor: '#10B981',
    borderRadius: 12,
    paddingHorizontal: 32,
    paddingVertical: 16,
    width: '100%',
    alignItems: 'center',
  },
  continueButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
});
